title: Inabikari Library
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
- jekyll-include-cache
- jekyll-titles-from-headings

minimal_mistakes_skin: "sunrise"
# "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single