title: Inabikari Library
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
- jekyll-include-cache

minimal_mistakes_skin: "sunrise"
# "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"